times=("Corinthians", "Palmeiras", "Santos", "Grêmio", "Cruzeiro")
print("-="*15)
print(f"Lista de times: {times}")
print("-="*15)
print(f"Os 2 primeiros são {times[0:2]}")
print("-="*15)
print(f"Os 2 ultimos são {times[-2:]}")
print("-="*15)
print(f"Ordem alfabética: {sorted(times)}")